export const ActionTypes = {
  FETCH_LOADING: 'FETCH_LOADING',
  FETCH_SUCCESS: 'FETCH_SUCCESS',
  FETCH_FAILURE: 'FETCH_FAILURE',
  SELECTED_STATE: 'SELECTED_STATE',
  SELECTED_CITY: 'SELECTED_CITY',
};
