export const ActionTypes = {
  FETCH_LOADING: 'FETCH_LOADING',
  FETCH_SUCCESS: 'FETCH_SUCCESS',
  FETCH_FAILURE: 'FETCH_FAILURE',
  FETCH_SUCCESS_CITYS: 'FETCH_SUCCESS_CITYS',
  FETCH_SUCCESS_DISTRICTS: 'FETCH_SUCCESS_DISTRICTS',
  FETCH_SUCCESS_MAP_CITY: 'FETCH_SUCCESS_MAP_CITY',
  FETCH_SUCCESS_MAP_BRAZIL: 'FETCH_SUCCESS_MAP_BRAZIL',
  SELECTED_STATE: 'SELECTED_STATE',
  SELECTED_CITY: 'SELECTED_CITY',
};
